(env) C:\Users\patel\OneDrive\Desktop\LJ\LJ PROJECTS\SEM4 PRO\GROUP\FurniFix\backend>python manage.py makemigrations
Traceback (most recent call last):
  File "C:\Users\patel\OneDrive\Desktop\LJ\LJ PROJECTS\SEM4 PRO\GROUP\FurniFix\backend\manage.py", line 22, in <module>
    main()
  File "C:\Users\patel\OneDrive\Desktop\LJ\LJ PROJECTS\SEM4 PRO\GROUP\FurniFix\backend\manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\patel\OneDrive\Desktop\LJ\LJ PROJECTS\SEM4 PRO\GROUP\FurniFix\env\Lib\site-packages\django\core\management\__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "C:\Users\patel\OneDrive\Desktop\LJ\LJ PROJECTS\SEM4 PRO\GROUP\FurniFix\env\Lib\site-packages\django\core\management\__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\patel\OneDrive\Desktop\LJ\LJ PROJECTS\SEM4 PRO\GROUP\FurniFix\env\Lib\site-packages\django\core\management\base.py", line 413, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\patel\OneDrive\Desktop\LJ\LJ PROJECTS\SEM4 PRO\GROUP\FurniFix\env\Lib\site-packages\django\core\management\base.py", line 454, in execute
    self.check()
  File "C:\Users\patel\OneDrive\Desktop\LJ\LJ PROJECTS\SEM4 PRO\GROUP\FurniFix\env\Lib\site-packages\django\core\management\base.py", line 486, in check
    all_issues = checks.run_checks(
                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\patel\OneDrive\Desktop\LJ\LJ PROJECTS\SEM4 PRO\GROUP\FurniFix\env\Lib\site-packages\django\core\checks\registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\patel\OneDrive\Desktop\LJ\LJ PROJECTS\SEM4 PRO\GROUP\FurniFix\env\Lib\site-packages\django\core\checks\urls.py", line 44, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\patel\OneDrive\Desktop\LJ\LJ PROJECTS\SEM4 PRO\GROUP\FurniFix\env\Lib\site-packages\django\core\checks\urls.py", line 63, in _load_all_namespaces
    url_patterns = getattr(resolver, "url_patterns", [])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\patel\OneDrive\Desktop\LJ\LJ PROJECTS\SEM4 PRO\GROUP\FurniFix\env\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\patel\OneDrive\Desktop\LJ\LJ PROJECTS\SEM4 PRO\GROUP\FurniFix\env\Lib\site-packages\django\urls\resolvers.py", line 718, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\patel\OneDrive\Desktop\LJ\LJ PROJECTS\SEM4 PRO\GROUP\FurniFix\env\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\patel\OneDrive\Desktop\LJ\LJ PROJECTS\SEM4 PRO\GROUP\FurniFix\env\Lib\site-packages\django\urls\resolvers.py", line 711, in urlconf_module
    return import_module(self.urlconf_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\patel\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "C:\Users\patel\OneDrive\Desktop\LJ\LJ PROJECTS\SEM4 PRO\GROUP\FurniFix\backend\backend\urls.py", line 21, in <module>
  File "C:\Users\patel\OneDrive\Desktop\LJ\LJ PROJECTS\SEM4 PRO\GROUP\FurniFix\backend\backend\urls.py", line 21, in <module>
    urlpatterns = [path("admin/", admin.site.urls), path("", include("apis.urls"))]
                                                             ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\patel\OneDrive\Desktop\LJ\LJ PROJECTS\SEM4 PRO\GROUP\FurniFix\env\Lib\site-packages\django\urls\conf.py", line 39, in include
    urlconf_module = import_module(urlconf_module)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\patel\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'apis.urls'